controller_hardware_resources = {
    "empty_L_controller": ["left_arm"],
    "jointspace_arm_L_controller": ["left_arm"],
    # "jointspace_arm_L_collisionfree_controller": ["left_arm"],
    "endpose_single_arm_qp_L_controller": ["left_arm"],
    "endpose_single_arm_qpik_L_controller": ["left_arm"],
    "jointspace_single_arm_qpik_L_controller": ["left_arm"],
    "moveit_left_arm_controller": ["left_arm"],

    "empty_R_controller": ["right_arm"],
    "jointspace_arm_R_controller": ["right_arm"],
    # "jointspace_arm_R_collisionfree_controller": ["right_arm"],
    "endpose_single_arm_qp_R_controller": ["right_arm"],
    "endpose_single_arm_qpik_R_controller": ["right_arm"],
    "jointspace_single_arm_qpik_R_controller": ["right_arm"],
    "moveit_right_arm_controller": ["right_arm"],

    # "jointspace_dual_arm_controller": ["left_arm", "right_arm"],
    "jointspace_ruckig_qp_controller": ["left_arm", "right_arm"],
    "endpose_dual_arm_qp_controller": ["left_arm", "right_arm"],
    "moveit_dual_arm_controller": ["left_arm", "right_arm"],


    "empty_head_controller": ["head"],
    "jointspace_head_controller": ["head"],
    "endpose_head_controller": ["head"],
    "moveit_head_controller": ["head"],

    "empty_body_controller": ["body"],
    "endpose_body_controller": ["body"],
    "jointspace_body_controller": ["body"],
    "jointspace_body3joints_controller": ["body"],
    "jointspace_waist_yaw_controller": ["body"],
    "jointspace_waist_pitch_controller": ["body"],
    "moveit_trunk_controller": ["body"],
}


jointstates_topic = {
    "tianyi2": "/joint_states",
    "tiangong2pro": "/joint_state_broadcaster/joint_states",
    "tiangong2dex": "/joint_state_broadcaster/joint_states",
    "tianyi_max": "/joint_states",
}

joints_name = {
    "tianyi2": [
        "shoulder_pitch_l_joint",
        "shoulder_roll_l_joint",
        "shoulder_yaw_l_joint",
        "elbow_pitch_l_joint",
        "elbow_yaw_l_joint",
        "wrist_pitch_l_joint",
        "wrist_roll_l_joint",
        "shoulder_pitch_r_joint",
        "shoulder_roll_r_joint",
        "shoulder_yaw_r_joint",
        "elbow_pitch_r_joint",
        "elbow_yaw_r_joint",
        "wrist_pitch_r_joint",
        "wrist_roll_r_joint",
        "first_leg_pitch_joint",
        "second_leg_pitch_joint",
        "waist_pitch_joint",
        "waist_yaw_joint",
        "head_yaw_joint",
        "head_pitch_joint",
        "head_roll_joint",
    ],
    "tianyi_max": [
        "shoulder_pitch_l_joint",
        "shoulder_roll_l_joint",
        "shoulder_yaw_l_joint",
        "elbow_pitch_l_joint",
        "elbow_yaw_l_joint",
        "wrist_pitch_l_joint",
        "wrist_roll_l_joint",
        "shoulder_pitch_r_joint",
        "shoulder_roll_r_joint",
        "shoulder_yaw_r_joint",
        "elbow_pitch_r_joint",
        "elbow_yaw_r_joint",
        "wrist_pitch_r_joint",
        "wrist_roll_r_joint",
        "first_leg_pitch_joint",
        "second_leg_pitch_joint",
        "waist_pitch_joint",
        "waist_yaw_joint",
        "head_yaw_joint",
        "head_pitch_joint",
        "head_roll_joint",
    ],
    "tiangong2pro": [
        "shoulder_pitch_l_joint",
        "shoulder_roll_l_joint",
        "shoulder_yaw_l_joint",
        "elbow_pitch_l_joint",
        "elbow_yaw_l_joint",
        "wrist_pitch_l_joint",
        "wrist_roll_l_joint",
        "shoulder_pitch_r_joint",
        "shoulder_roll_r_joint",
        "shoulder_yaw_r_joint",
        "elbow_pitch_r_joint",
        "elbow_yaw_r_joint",
        "wrist_pitch_r_joint",
        "wrist_roll_r_joint",
    ],
    "tiangong2dex": [
        "shoulder_pitch_l_joint",
        "shoulder_roll_l_joint",
        "shoulder_yaw_l_joint",
        "elbow_pitch_l_joint",
        "elbow_yaw_l_joint",
        "wrist_pitch_l_joint",
        "wrist_roll_l_joint",
        "shoulder_pitch_r_joint",
        "shoulder_roll_r_joint",
        "shoulder_yaw_r_joint",
        "elbow_pitch_r_joint",
        "elbow_yaw_r_joint",
        "wrist_pitch_r_joint",
        "wrist_roll_r_joint",
    ],
}